# Generated by Django 2.1.15 on 2020-02-04 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='iser',
            new_name='user',
        ),
    ]
